name: Publish Public Package

on:
  push:
    branches:
    - main
    - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build package
        run: npm run rollup

      - name: Bump version
        run: npm version patch -m "Bump version to %s [skip ci]"

      - name: Push version bump back to repo
        run: git push

      - name: Publish to npm
        run: npm publish --provenance --access public
